# Generated by Django 5.0.1 on 2024-01-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='business_category',
            field=models.CharField(choices=[('individual', 'Individual/Freelancer'), ('accounting', 'Accounting and Bookkeeping')], max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='customers',
            field=models.ManyToManyField(blank=True, related_name='profile_customers', to='users.customer'),
        ),
    ]
