# Generated by Django 5.0.1 on 2024-01-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicepilot_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice_date_generated',
            field=models.DateTimeField(),
        ),
    ]
