# Generated by Django 5.0.1 on 2024-01-21 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoicepilot_app", "0002_clientcontact_invoiceitem_notification_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientcontact",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="clientcontact",
            name="user",
        ),
        migrations.AddField(
            model_name="invoice",
            name="recipent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="invoicepilot_app.clientcontact",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="recipent_email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="invoicepilot_app.invoice",
            ),
        ),
        migrations.CreateModel(
            name="MailRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("to", models.EmailField(max_length=254)),
                ("date_sent", models.DateTimeField(auto_now_add=True)),
                ("template_used", models.CharField(default="default", max_length=20)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mail_records",
                        to="invoicepilot_app.invoice",
                    ),
                ),
            ],
        ),
    ]
