# Generated by Django 5.0.1 on 2024-01-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_contact_firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_contact_lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('work_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField()),
            ],
        ),
    ]
