# Generated by Django 5.0.1 on 2024-01-24 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company_name',
            field=models.CharField(default='DefaultCompanyName', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_phone_mobile',
            field=models.CharField(blank=True, default='DefaultPhoneMobile', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_phone_work',
            field=models.CharField(blank=True, default='DefaultPhoneWork', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('Business', 'Business'), ('Individual', 'Individual')], default='Individual', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='primary_contact_first_name',
            field=models.CharField(default='DefaultFirstName', max_length=30),
        ),
        migrations.AddField(
            model_name='customer',
            name='primary_contact_last_name',
            field=models.CharField(default='DefaultLastName', max_length=30),
        ),
    ]
