# Generated by Django 5.0.1 on 2024-01-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaccount', '0002_rename_full_name_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='business_category',
            field=models.CharField(choices=[('individual', 'Individual/Freelancer'), ('Business', 'Business/Company')], max_length=50),
        ),
    ]
